# Site settings
title: Welcome
description: 谢嘉康的简历
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 谢嘉康
user_description: 坐标上海, 26岁, 3年iOS开发经验
user_title: Software Developer
email: xtuphe@live.com
twitter_username: xtuphe
github_username:  xtuphe
gplus_username:  xtuphe

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
