# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Xtuphe
tagline:          'A tagline'
description:      '一个新的空空的个人地址， 没事去瞅一下我的<a href="http://www.jianshu.com/u/91199b2895fe" target="_blank">简书</a>'
url:              http://www.jianshu.com/u/91199b2895fe
baseurl:          /

author:
  name:           'Xtuphe'
  url:            http://www.jianshu.com/u/91199b2895fe

paginate:         2

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/xtuphe/xtuphe.github.io
