# Site settings
title: Welcome
description: A blog about lllllllllllllllaaaaaaaaaaaaaaaaaaaaaaaaaa
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Xtuphe
user_description: 一个很勤快的懒人。(๑•̀ㅂ•́)و✧加油
user_title: Software Developer
email: xtuphe@live.com
twitter_username: xtuphe
github_username:  xtuphe
gplus_username:  xtuphe
